In [3]:
### LU decomposition for square matrix

In [4]:
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([[3, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# LU decomposition
P, L, U = lu(A)
print(P)
print(L)
print(U)
# reconstruct
B = P.dot(L).dot(U)
c = L.dot(U)
print(c)
print(B)

[[3 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.          0.          0.        ]
 [ 0.42857143  1.          0.        ]
 [ 0.57142857 -0.3         1.        ]]
[[ 7.          8.          9.        ]
 [ 0.         -1.42857143 -0.85714286]
 [ 0.          0.          0.6       ]]
[[7. 8. 9.]
 [3. 2. 3.]
 [4. 5. 6.]]
[[3. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [6]:

# QR decomposition
from numpy import array
from numpy.linalg import qr
# define a 3x2 matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# QR decomposition
Q, R = qr(A, 'complete')
print(Q.shape,R.shape)
print(Q)
print(R)
# reconstruct
B = Q.dot(R)
print(B)


[[1 2]
 [3 4]
 [5 6]]
(3, 3) (3, 2)
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [7]:
from numpy import array
from numpy.linalg import cholesky
# define a 3x3 matrix
A = array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
print(A)
# Cholesky decomposition
L = cholesky(A)
print(L)
# reconstruct
B = L.dot(L.T)
print(B)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
